In [1]:
import os
wd = os.environ.get('TRAJECTORY_WORKDIR', '/workspace')
print(wd)
for root, dirs, files in os.walk('/workspace'):
    # Skip hidden and memory
    dirs[:] = [d for d in dirs if not d.startswith('.') and d != 'memory' and d != 'node_modules']
    depth = root.count('/') - 1
    if depth > 3:
        continue
    print(root)
    for f in files[:30]:
        print(' ', f)

/workspace/3f37bef1-8d91-4a59-ae17-3a7771cf49c9
/workspace
/workspace/3f37bef1-8d91-4a59-ae17-3a7771cf49c9
  bibliography-validation.md
  PLAN.md
  DATA_INVENTORY.md
  paper.pdf
  run_summary.csv
  .kernel_llm_logs_1.txt
  design_coverage.png
  references.bib
  assessment.md
  RyanWeber_microstructure_report.pdf
  evaluation_report.md
  paper.tex
/workspace/3f37bef1-8d91-4a59-ae17-3a7771cf49c9/extracted-context
  parts_list.md
  schematic_support_stand.md
  README.md
  schematic_induction_furnace.md
  SOP_alternate.md
  useful_links.md
  order_corrections_coils.md
  SOP_induction_200901.md
/workspace/3f37bef1-8d91-4a59-ae17-3a7771cf49c9/notebooks
  af283377-d344-4b4f-bb06-8ca174a2977e.ipynb
/workspace/3f37bef1-8d91-4a59-ae17-3a7771cf49c9/run-plots
  IFrun072_Ni4N5_079,080_1400C_12h.png
  IFrun038_Ni4N5_025_1300C_1h.csv
  IFrun081_Ni200_015_1325C_20h.png
  IFrun032_Ni4N5_022_1400C_10min.csv
  IFrun079_Ni4N5_084_1300C_12h.csv
  IFrun079_Ni4N5_084_1300C_12h.png
  IFrun040_Ni4N5_027_1250C_6h.png
  IFrun080_Ni200_017_1325C_40h.csv
  IFrun039_Ni4N5_026_1200C_6h.csv
  IFrun039_Ni4N5_026_1200C_6h.png
  IFrun081_Ni200_015_1325C_20h.csv
  IFrun038_Ni4N5_025_1300C_1h.png
  IFrun072_Ni4N5_079,080_1400C_12h.csv
  IFrun032_Ni4N5_022_1400C_10min.png
  IFrun040_Ni4N5_027_1250C_6h.csv
  IFrun049_Ni4N5_034_1200C_12h.csv
  IFrun049_Ni4N5_034_1200C_12h.png
  IFrun080_Ni200_017_1325C_40h.png

In [2]:
import pandas as pd
df = pd.read_csv(f'{wd}/run_summary.csv')
print(df.shape)
print(df.columns.tolist())
df.head()

(49, 7)
['run', 'source', 'points', 'duration_min', 'peak_temp_C', 'soak_temp_C', 'has_flow']

,run,source,points,duration_min,peak_temp_C,soak_temp_C,has_flow
0,IFrun016_Ni4N5_010,docs/data_log/IFrun001-020/IFrun016_Ni4N5_010....,18136,1478.0,1211.1,1199.9,no
1,IFrun017_Ni4N5_011,docs/data_log/IFrun001-020/IFrun017_Ni4N5_011....,7641,194.9,1258.6,1249.9,no
2,IFrun018_Ni4N5_011,docs/data_log/IFrun001-020/IFrun018_Ni4N5_011....,19008,1523.7,1311.0,1299.8,no
3,IFrun019_Ni4N5_012,docs/data_log/IFrun001-020/IFrun019_Ni4N5_012....,15481,991.2,1214.7,1199.6,no
4,IFrun020_Ni4N5_013,docs/data_log/IFrun001-020/IFrun020_Ni4N5_013....,11221,374.2,1261.4,1250.4,no

In [3]:
df.sort_values(['soak_temp_C','duration_min'])

,run,source,points,duration_min,peak_temp_C,soak_temp_C,has_flow
48,checktestdata,docs/data_log/checktestdata.xlsx,8,0.3,799.0,799.0,no
9,Ni4N5_001b_IFrun006,docs/data_log/IFrun001-020/Ni4N5_001b_IFrun006...,42,1.3,799.0,799.0,no
36,IFrun075_evap_Ni4N5_053_Pd_001a_900C_10min,docs/data_log/IFrun061-080/IFrun075_evap_Ni4N5...,700,11.7,801.4,799.5,yes
46,IFrun085_Ni4N5_087_1300C_20h,docs/data_log/IFrun081-100/IFrun085_Ni4N5_087_...,700,11.7,799.8,799.5,yes
15,IFrun035_crucible_1150C_10min,docs/data_log/IFrun021-040/IFrun035_crucible_1...,3940,32.8,860.5,799.5,no
10,Ni4N5_002_IFrun007,docs/data_log/IFrun001-020/Ni4N5_002_IFrun007....,1437,50.7,799.7,799.6,no
6,Ni200_001_IFrun004,docs/data_log/IFrun001-020/Ni200_001_IFrun004....,1017,51.0,799.6,799.6,no
11,Ni4N5_002_IFrun008,docs/data_log/IFrun001-020/Ni4N5_002_IFrun008....,11012,183.5,799.6,799.6,no
34,IFrun073_evapDryRun_900C_10min,docs/data_log/IFrun061-080/IFrun073_evapDryRun...,400,33.2,933.3,900.2,yes
35,IFrun074_evap_Ni4N5_053_Pd_001a_900C_10min,docs/data_log/IFrun061-080/IFrun074_evap_Ni4N5...,900,15.0,967.7,901.1,yes
12,Ni4N5_002_IFrun009,docs/data_log/IFrun001-020/Ni4N5_002_IFrun009....,535,26.8,1031.3,1031.3,no
27,"IFrun057_Ni4N5_049,050_1200C_12h - Copy","docs/data_log/IFrun041-060/IFrun057_Ni4N5_049,...",2800,46.6,1092.5,1058.1,yes
16,IFrun036_crucible_1100C_5min,docs/data_log/IFrun021-040/IFrun036_crucible_1...,6090,50.7,1114.8,1098.0,no
37,IFrun076_evap_Ni4N5_053_Pd_001a_1100C_10min,docs/data_log/IFrun061-080/IFrun076_evap_Ni4N5...,3100,51.6,1111.2,1098.3,yes
17,IFrun037_crucible_1100C_5min,docs/data_log/IFrun021-040/IFrun037_crucible_1...,5970,49.7,1112.0,1098.4,no
38,IFrun077_evap_Ni4N5_053_Pd_001a_1200C_10min,docs/data_log/IFrun061-080/IFrun077_evap_Ni4N5...,3200,53.3,1204.5,1199.3,yes
3,IFrun019_Ni4N5_012,docs/data_log/IFrun001-020/IFrun019_Ni4N5_012....,15481,991.2,1214.7,1199.6,no
22,IFrun052_Ni4N5_040_1200C_12h,docs/data_log/IFrun041-060/IFrun052_Ni4N5_040_...,45400,756.6,1206.8,1199.8,yes
0,IFrun016_Ni4N5_010,docs/data_log/IFrun001-020/IFrun016_Ni4N5_010....,18136,1478.0,1211.1,1199.9,no
21,IFrun049_Ni4N5_034_1200C_12h,docs/data_log/IFrun041-060/IFrun049_Ni4N5_034_...,8900,741.6,1223.9,1200.0,no
19,IFrun039_Ni4N5_026_1200C_6h,docs/data_log/IFrun021-040/IFrun039_Ni4N5_026_...,51590,429.9,1219.3,1200.2,no
30,"IFrun059_Ni4N5_053,054_1200C_12h","docs/data_log/IFrun041-060/IFrun059_Ni4N5_053,...",45500,758.3,1209.0,1200.3,yes
25,"IFrun056_Ni4N5_047,048_1200C_12h (enterprise1....","docs/data_log/IFrun041-060/IFrun056_Ni4N5_047,...",45600,760.0,1209.1,1200.6,yes
26,"IFrun056_Ni4N5_047,048_1200C_12h","docs/data_log/IFrun041-060/IFrun056_Ni4N5_047,...",45600,760.0,1209.1,1200.6,yes
31,"IFrun060_Ni4N5_056,057_1200C_12h","docs/data_log/IFrun041-060/IFrun060_Ni4N5_056,...",45500,758.3,1209.7,1200.8,yes
29,"IFrun058_Ni4N5_051,052_1200C_12h","docs/data_log/IFrun041-060/IFrun058_Ni4N5_051,...",45500,758.3,1210.5,1200.9,yes
28,"IFrun057_Ni4N5_049,050_1200C_12h","docs/data_log/IFrun041-060/IFrun057_Ni4N5_049,...",48000,800.0,1210.2,1201.2,yes
23,"IFrun054_Ni4N5_042,044_1200C_12h","docs/data_log/IFrun041-060/IFrun054_Ni4N5_042,...",45600,760.0,1227.0,1201.3,yes
24,"IFrun055_Ni4N5_045,046_1200C_12h","docs/data_log/IFrun041-060/IFrun055_Ni4N5_045,...",46700,778.3,1218.4,1204.1,yes
20,IFrun040_Ni4N5_027_1250C_6h,docs/data_log/IFrun021-040/IFrun040_Ni4N5_027_...,48280,402.3,1260.7,1249.3,no
1,IFrun017_Ni4N5_011,docs/data_log/IFrun001-020/IFrun017_Ni4N5_011....,7641,194.9,1258.6,1249.9,no
4,IFrun020_Ni4N5_013,docs/data_log/IFrun001-020/IFrun020_Ni4N5_013....,11221,374.2,1261.4,1250.4,no
18,IFrun038_Ni4N5_025_1300C_1h,docs/data_log/IFrun021-040/IFrun038_Ni4N5_025_...,5740,47.8,1310.9,1297.0,no
39,IFrun078_evap_Ni4N5_053_Pd_001a_1300C_10min,docs/data_log/IFrun061-080/IFrun078_evap_Ni4N5...,3300,55.0,1305.7,1299.1,yes
2,IFrun018_Ni4N5_011,docs/data_log/IFrun001-020/IFrun018_Ni4N5_011....,19008,1523.7,1311.0,1299.8,no
44,IFrun083_Ni4N5_083_1300C_20h,docs/data_log/IFrun081-100/IFrun083_Ni4N5_083_...,75100,1251.7,1307.4,1300.8,yes
45,IFrun084_Ni4N5_086_1300C_20h,docs/data_log/IFrun081-100/IFrun084_Ni4N5_086_...,53900,898.3,1313.3,1301.1,yes
43,IFrun082_Ni4N5_081_1300C_20h,docs/data_log/IFrun081-100/IFrun082_Ni4N5_081_...,71200,1186.7,1310.9,1301.4,yes
40,IFrun079_Ni4N5_084_1300C_12h,docs/data_log/IFrun061-080/IFrun079_Ni4N5_084_...,46100,768.3,1311.9,1302.0,yes
14,IFrun034_Ni4N5_024_1400C_5min,docs/data_log/IFrun021-040/IFrun034_Ni4N5_024_...,12528,600.5,1373.1,1317.9,no
42,IFrun081_Ni200_015_1325C_20h,docs/data_log/IFrun081-100/IFrun081_Ni200_015_...,74500,1241.7,1334.2,1326.4,yes
41,IFrun080_Ni200_017_1325C_40h,docs/data_log/IFrun061-080/IFrun080_Ni200_017_...,14900,2483.2,1349.9,1330.7,yes
32,"IFrun071_Ni4N5_077,078_1350C_12h","docs/data_log/IFrun061-080/IFrun071_Ni4N5_077,...",9200,766.6,1361.3,1351.2,yes
13,IFrun032_Ni4N5_022_1400C_10min,docs/data_log/IFrun021-040/IFrun032_Ni4N5_022_...,2270,76.9,1458.6,1397.9,no
33,"IFrun072_Ni4N5_079,080_1400C_12h","docs/data_log/IFrun061-080/IFrun072_Ni4N5_079,...",9200,766.6,1412.5,1401.5,yes
47,trent_test1,docs/data_log/Trent_SS/trent_test1.xlsx,490,8.2,NaN,NaN,no
7,Ni200_001_IFrun005,docs/data_log/IFrun001-020/Ni200_001_IFrun005.lvm,1866,22.8,NaN,NaN,no
5,Ni200_001_IFrun004,docs/data_log/IFrun001-020/Ni200_001_IFrun004.lvm,7,86.7,NaN,NaN,no
8,Ni200_001_IFrun005,docs/data_log/IFrun001-020/Ni200_001_IFrun005....,14782,725.3,NaN,NaN,no

In [4]:
import pandas as pd
pd.set_option('display.max_rows', 100)
pd.set_option('display.width', 200)
print(df.sort_values(['soak_temp_C','duration_min']).to_string())

                                                                  run                                                                                             source  points  duration_min  peak_temp_C  soak_temp_C has_flow
48                                                      checktestdata                                                                   docs/data_log/checktestdata.xlsx       8           0.3        799.0        799.0       no
9                                                 Ni4N5_001b_IFrun006                                                docs/data_log/IFrun001-020/Ni4N5_001b_IFrun006.xlsx      42           1.3        799.0        799.0       no
36                         IFrun075_evap_Ni4N5_053_Pd_001a_900C_10min                         docs/data_log/IFrun061-080/IFrun075_evap_Ni4N5_053_Pd_001a_900C_10min.xlsx     700          11.7        801.4        799.5      yes
46                                       IFrun085_Ni4N5_087_1300C_20h                                       docs/data_log/IFrun081-100/IFrun085_Ni4N5_087_1300C_20h.xlsx     700          11.7        799.8        799.5      yes
15                                      IFrun035_crucible_1150C_10min                                      docs/data_log/IFrun021-040/IFrun035_crucible_1150C_10min.xlsx    3940          32.8        860.5        799.5       no
10                                                 Ni4N5_002_IFrun007                                                 docs/data_log/IFrun001-020/Ni4N5_002_IFrun007.xlsx    1437          50.7        799.7        799.6       no
6                                                  Ni200_001_IFrun004                                                 docs/data_log/IFrun001-020/Ni200_001_IFrun004.xlsx    1017          51.0        799.6        799.6       no
11                                                 Ni4N5_002_IFrun008                                                 docs/data_log/IFrun001-020/Ni4N5_002_IFrun008.xlsx   11012         183.5        799.6        799.6       no
34                                     IFrun073_evapDryRun_900C_10min                                     docs/data_log/IFrun061-080/IFrun073_evapDryRun_900C_10min.xlsx     400          33.2        933.3        900.2      yes
35                         IFrun074_evap_Ni4N5_053_Pd_001a_900C_10min                         docs/data_log/IFrun061-080/IFrun074_evap_Ni4N5_053_Pd_001a_900C_10min.xlsx     900          15.0        967.7        901.1      yes
12                                                 Ni4N5_002_IFrun009                                                 docs/data_log/IFrun001-020/Ni4N5_002_IFrun009.xlsx     535          26.8       1031.3       1031.3       no
27                            IFrun057_Ni4N5_049,050_1200C_12h - Copy                            docs/data_log/IFrun041-060/IFrun057_Ni4N5_049,050_1200C_12h - Copy.xlsx    2800          46.6       1092.5       1058.1      yes
16                                       IFrun036_crucible_1100C_5min                                       docs/data_log/IFrun021-040/IFrun036_crucible_1100C_5min.xlsx    6090          50.7       1114.8       1098.0       no
37                        IFrun076_evap_Ni4N5_053_Pd_001a_1100C_10min                        docs/data_log/IFrun061-080/IFrun076_evap_Ni4N5_053_Pd_001a_1100C_10min.xlsx    3100          51.6       1111.2       1098.3      yes
17                                       IFrun037_crucible_1100C_5min                                       docs/data_log/IFrun021-040/IFrun037_crucible_1100C_5min.xlsx    5970          49.7       1112.0       1098.4       no
38                        IFrun077_evap_Ni4N5_053_Pd_001a_1200C_10min                        docs/data_log/IFrun061-080/IFrun077_evap_Ni4N5_053_Pd_001a_1200C_10min.xlsx    3200          53.3       1204.5       1199.3      yes
3                                                  IFrun019_Ni4N5_012                                                 docs/data_log/IFrun001-020/IFrun019_Ni4N5_012.xlsx   15481         991.2       1214.7       1199.6       no
22                                       IFrun052_Ni4N5_040_1200C_12h                                       docs/data_log/IFrun041-060/IFrun052_Ni4N5_040_1200C_12h.xlsx   45400         756.6       1206.8       1199.8      yes
0                                                  IFrun016_Ni4N5_010                                                 docs/data_log/IFrun001-020/IFrun016_Ni4N5_010.xlsx   18136        1478.0       1211.1       1199.9       no
21                                       IFrun049_Ni4N5_034_1200C_12h                                       docs/data_log/IFrun041-060/IFrun049_Ni4N5_034_1200C_12h.xlsx    8900         741.6       1223.9       1200.0       no
19                                        IFrun039_Ni4N5_026_1200C_6h                                        docs/data_log/IFrun021-040/IFrun039_Ni4N5_026_1200C_6h.xlsx   51590         429.9       1219.3       1200.2       no
30                                   IFrun059_Ni4N5_053,054_1200C_12h                                   docs/data_log/IFrun041-060/IFrun059_Ni4N5_053,054_1200C_12h.xlsx   45500         758.3       1209.0       1200.3      yes
25  IFrun056_Ni4N5_047,048_1200C_12h (enterprise1.sterling@gmail.com)  docs/data_log/IFrun041-060/IFrun056_Ni4N5_047,048_1200C_12h (enterprise1.sterling@gmail.com).xlsx   45600         760.0       1209.1       1200.6      yes
26                                   IFrun056_Ni4N5_047,048_1200C_12h                                   docs/data_log/IFrun041-060/IFrun056_Ni4N5_047,048_1200C_12h.xlsx   45600         760.0       1209.1       1200.6      yes
31                                   IFrun060_Ni4N5_056,057_1200C_12h                                   docs/data_log/IFrun041-060/IFrun060_Ni4N5_056,057_1200C_12h.xlsx   45500         758.3       1209.7       1200.8      yes
29                                   IFrun058_Ni4N5_051,052_1200C_12h                                   docs/data_log/IFrun041-060/IFrun058_Ni4N5_051,052_1200C_12h.xlsx   45500         758.3       1210.5       1200.9      yes
28                                   IFrun057_Ni4N5_049,050_1200C_12h                                   docs/data_log/IFrun041-060/IFrun057_Ni4N5_049,050_1200C_12h.xlsx   48000         800.0       1210.2       1201.2      yes
23                                   IFrun054_Ni4N5_042,044_1200C_12h                                   docs/data_log/IFrun041-060/IFrun054_Ni4N5_042,044_1200C_12h.xlsx   45600         760.0       1227.0       1201.3      yes
24                                   IFrun055_Ni4N5_045,046_1200C_12h                                   docs/data_log/IFrun041-060/IFrun055_Ni4N5_045,046_1200C_12h.xlsx   46700         778.3       1218.4       1204.1      yes
20                                        IFrun040_Ni4N5_027_1250C_6h                                        docs/data_log/IFrun021-040/IFrun040_Ni4N5_027_1250C_6h.xlsx   48280         402.3       1260.7       1249.3       no
1                                                  IFrun017_Ni4N5_011                                                 docs/data_log/IFrun001-020/IFrun017_Ni4N5_011.xlsx    7641         194.9       1258.6       1249.9       no
4                                                  IFrun020_Ni4N5_013                                                 docs/data_log/IFrun001-020/IFrun020_Ni4N5_013.xlsx   11221         374.2       1261.4       1250.4       no
18                                        IFrun038_Ni4N5_025_1300C_1h                                        docs/data_log/IFrun021-040/IFrun038_Ni4N5_025_1300C_1h.xlsx    5740          47.8       1310.9       1297.0       no
39                        IFrun078_evap_Ni4N5_053_Pd_001a_1300C_10min                        docs/data_log/IFrun061-080/IFrun078_evap_Ni4N5_053_Pd_001a_1300C_10min.xlsx    3300          55.0       1305.7       1299.1      yes
2                                                  IFrun018_Ni4N5_011                                                 docs/data_log/IFrun001-020/IFrun018_Ni4N5_011.xlsx   19008        1523.7       1311.0       1299.8       no
44                                       IFrun083_Ni4N5_083_1300C_20h                                       docs/data_log/IFrun081-100/IFrun083_Ni4N5_083_1300C_20h.xlsx   75100        1251.7       1307.4       1300.8      yes
45                                       IFrun084_Ni4N5_086_1300C_20h                                       docs/data_log/IFrun081-100/IFrun084_Ni4N5_086_1300C_20h.xlsx   53900         898.3       1313.3       1301.1      yes
43                                       IFrun082_Ni4N5_081_1300C_20h                                       docs/data_log/IFrun081-100/IFrun082_Ni4N5_081_1300C_20h.xlsx   71200        1186.7       1310.9       1301.4      yes
40                                       IFrun079_Ni4N5_084_1300C_12h                                       docs/data_log/IFrun061-080/IFrun079_Ni4N5_084_1300C_12h.xlsx   46100         768.3       1311.9       1302.0      yes
14                                      IFrun034_Ni4N5_024_1400C_5min                                      docs/data_log/IFrun021-040/IFrun034_Ni4N5_024_1400C_5min.xlsx   12528         600.5       1373.1       1317.9       no
42                                       IFrun081_Ni200_015_1325C_20h                                       docs/data_log/IFrun081-100/IFrun081_Ni200_015_1325C_20h.xlsx   74500        1241.7       1334.2       1326.4      yes
41                                       IFrun080_Ni200_017_1325C_40h                                       docs/data_log/IFrun061-080/IFrun080_Ni200_017_1325C_40h.xlsx   14900        2483.2       1349.9       1330.7      yes
32                                   IFrun071_Ni4N5_077,078_1350C_12h                                   docs/data_log/IFrun061-080/IFrun071_Ni4N5_077,078_1350C_12h.xlsx    9200         766.6       1361.3       1351.2      yes
13                                     IFrun032_Ni4N5_022_1400C_10min                                     docs/data_log/IFrun021-040/IFrun032_Ni4N5_022_1400C_10min.xlsx    2270          76.9       1458.6       1397.9       no
33                                   IFrun072_Ni4N5_079,080_1400C_12h                                   docs/data_log/IFrun061-080/IFrun072_Ni4N5_079,080_1400C_12h.xlsx    9200         766.6       1412.5       1401.5      yes
47                                                        trent_test1                                                            docs/data_log/Trent_SS/trent_test1.xlsx     490           8.2          NaN          NaN       no
7                                                  Ni200_001_IFrun005                                                  docs/data_log/IFrun001-020/Ni200_001_IFrun005.lvm    1866          22.8          NaN          NaN       no
5                                                  Ni200_001_IFrun004                                                  docs/data_log/IFrun001-020/Ni200_001_IFrun004.lvm       7          86.7          NaN          NaN       no
8                                                  Ni200_001_IFrun005                                                 docs/data_log/IFrun001-020/Ni200_001_IFrun005.xlsx   14782         725.3          NaN          NaN       no

In [5]:
# 1200C/12h Ni4N5 replicate group
rep = df[(df['soak_temp_C'].between(1199.0, 1205.0)) & (df['duration_min'].between(700, 1600)) & (df['run'].str.contains('Ni4N5', case=False, na=False))]
print(rep[['run','points','duration_min','peak_temp_C','soak_temp_C','has_flow']].to_string())
print('\nn =', len(rep))
print('Soak T mean/sd:', rep['soak_temp_C'].mean(), rep['soak_temp_C'].std())
print('Peak T mean/sd:', rep['peak_temp_C'].mean(), rep['peak_temp_C'].std())
print('Duration mean/sd (min):', rep['duration_min'].mean(), rep['duration_min'].std())

                                                                  run  points  duration_min  peak_temp_C  soak_temp_C has_flow
0                                                  IFrun016_Ni4N5_010   18136        1478.0       1211.1       1199.9       no
3                                                  IFrun019_Ni4N5_012   15481         991.2       1214.7       1199.6       no
21                                       IFrun049_Ni4N5_034_1200C_12h    8900         741.6       1223.9       1200.0       no
22                                       IFrun052_Ni4N5_040_1200C_12h   45400         756.6       1206.8       1199.8      yes
23                                   IFrun054_Ni4N5_042,044_1200C_12h   45600         760.0       1227.0       1201.3      yes
24                                   IFrun055_Ni4N5_045,046_1200C_12h   46700         778.3       1218.4       1204.1      yes
25  IFrun056_Ni4N5_047,048_1200C_12h (enterprise1.sterling@gmail.com)   45600         760.0       1209.1       1200.6      yes
26                                   IFrun056_Ni4N5_047,048_1200C_12h   45600         760.0       1209.1       1200.6      yes
28                                   IFrun057_Ni4N5_049,050_1200C_12h   48000         800.0       1210.2       1201.2      yes
29                                   IFrun058_Ni4N5_051,052_1200C_12h   45500         758.3       1210.5       1200.9      yes
30                                   IFrun059_Ni4N5_053,054_1200C_12h   45500         758.3       1209.0       1200.3      yes
31                                   IFrun060_Ni4N5_056,057_1200C_12h   45500         758.3       1209.7       1200.8      yes

n = 12
Soak T mean/sd: 1200.7583333333332 1.1874023085813041
Peak T mean/sd: 1213.2916666666667 6.461699513754958
Duration mean/sd (min): 841.7166666666666 211.30326260585468

In [6]:
# Filter to the IFrun052-060 cohort specifically (the "same profile/material/geometry" group with has_flow=yes)
cohort = df[df['run'].str.match(r'IFrun05[2-9]_Ni4N5.*1200C_12h$|IFrun060_Ni4N5.*1200C_12h$')]
print(cohort[['run','duration_min','peak_temp_C','soak_temp_C','has_flow']].to_string())
print('\nn =', len(cohort))
print('Soak T mean:', cohort['soak_temp_C'].mean(), 'SD:', cohort['soak_temp_C'].std())
print('Peak T mean:', cohort['peak_temp_C'].mean(), 'SD:', cohort['peak_temp_C'].std())
print('Duration mean (min):', cohort['duration_min'].mean(), 'SD:', cohort['duration_min'].std())

                                 run  duration_min  peak_temp_C  soak_temp_C has_flow
22      IFrun052_Ni4N5_040_1200C_12h         756.6       1206.8       1199.8      yes
23  IFrun054_Ni4N5_042,044_1200C_12h         760.0       1227.0       1201.3      yes
24  IFrun055_Ni4N5_045,046_1200C_12h         778.3       1218.4       1204.1      yes
26  IFrun056_Ni4N5_047,048_1200C_12h         760.0       1209.1       1200.6      yes
28  IFrun057_Ni4N5_049,050_1200C_12h         800.0       1210.2       1201.2      yes
29  IFrun058_Ni4N5_051,052_1200C_12h         758.3       1210.5       1200.9      yes
30  IFrun059_Ni4N5_053,054_1200C_12h         758.3       1209.0       1200.3      yes
31  IFrun060_Ni4N5_056,057_1200C_12h         758.3       1209.7       1200.8      yes

n = 8
Soak T mean: 1201.125 SD: 1.295872568690948
Peak T mean: 1212.5875 SD: 6.744614253504175
Duration mean (min): 766.2249999999999 SD: 15.330245548308373

In [7]:
# Look at per-run CSV (one of the run-plots CSVs) to see structure
import os
csvs = sorted([f for f in os.listdir(f'{wd}/run-plots') if f.endswith('.csv')])
print(csvs)
sample = pd.read_csv(f'{wd}/run-plots/{csvs[0]}')
print(sample.shape, sample.columns.tolist())
sample.head()

['IFrun032_Ni4N5_022_1400C_10min.csv', 'IFrun038_Ni4N5_025_1300C_1h.csv', 'IFrun039_Ni4N5_026_1200C_6h.csv', 'IFrun040_Ni4N5_027_1250C_6h.csv', 'IFrun049_Ni4N5_034_1200C_12h.csv', 'IFrun072_Ni4N5_079,080_1400C_12h.csv', 'IFrun079_Ni4N5_084_1300C_12h.csv', 'IFrun080_Ni200_017_1325C_40h.csv', 'IFrun081_Ni200_015_1325C_20h.csv']
(2270, 3) ['elapsed_s', 'power_mA', 'temperature_C']

   elapsed_s  power_mA  temperature_C
0      0.000    0.0010          799.4
1      2.033    0.0010          799.5
2      4.066    0.0010          799.5
3      6.099    0.0208          799.5
4      8.132    0.0604          799.6

In [8]:
import numpy as np

def control_metrics(csv_path, setpoint, soak_pad_s=120, deadband_C=10):
    d = pd.read_csv(csv_path)
    t = d['elapsed_s'].values
    T = d['temperature_C'].values
    P = d['power_mA'].values
    # Define "soak" by temperature within setpoint band
    in_band = np.abs(T - setpoint) <= deadband_C
    if not in_band.any():
        return None
    # First crossing of (setpoint - deadband) -> rise; first time entering band -> settle time
    idx_band = np.where(in_band)[0]
    soak_start = idx_band[0]
    soak_end = idx_band[-1]
    # Rise time: 10% to 90% from start to soak setpoint
    T0 = T[0]
    span = setpoint - T0
    t10 = t[np.argmax(T >= T0 + 0.1*span)] if (T >= T0 + 0.1*span).any() else np.nan
    t90 = t[np.argmax(T >= T0 + 0.9*span)] if (T >= T0 + 0.9*span).any() else np.nan
    rise = t90 - t10
    # Overshoot
    peak = T[:soak_end+1].max()
    overshoot = peak - setpoint
    # Settling time: time from t10 until T stays within deadband for >= soak_pad_s
    settle_t = np.nan
    for i in range(soak_start, len(T)):
        # check if from here onward stays in band for soak_pad_s
        window_end = t[i] + soak_pad_s
        j = np.searchsorted(t, window_end)
        if j > i and np.all(in_band[i:j]):
            settle_t = t[i] - t10
            break
    # Soak window: where in band continuously after settle
    soak_T = T[soak_start:soak_end+1][in_band[soak_start:soak_end+1]]
    soak_mean = soak_T.mean()
    soak_sd = soak_T.std(ddof=1)
    max_dev = np.max(np.abs(soak_T - setpoint))
    soak_dur_min = (t[soak_end] - t[soak_start]) / 60.0
    # Linear drift across soak (degrees per hour)
    soak_t_in = t[soak_start:soak_end+1]
    if len(soak_t_in) > 5:
        coef = np.polyfit(soak_t_in, T[soak_start:soak_end+1], 1)
        drift_per_hr = coef[0] * 3600
    else:
        drift_per_hr = np.nan
    return {
        'setpoint_C': setpoint,
        'rise_10_90_s': rise,
        'overshoot_C': overshoot,
        'settle_to_band_s': settle_t,
        'soak_mean_C': soak_mean,
        'soak_sd_C': soak_sd,
        'soak_max_dev_C': max_dev,
        'soak_duration_min': soak_dur_min,
        'soak_drift_C_per_hr': drift_per_hr,
        'soak_n_points': len(soak_T),
    }

# Compute for all available per-run CSVs using soak_temp_C from run_summary
results = []
df['run_key'] = df['run'].str.replace(r' \(.*\)$', '', regex=True)
for f in csvs:
    run_id = f.replace('.csv','')
    row = df[df['run'] == run_id]
    if row.empty:
        continue
    sp = row['soak_temp_C'].values[0]
    # Use the nominal setpoint from filename if available
    # parse e.g. "1400C" => 1400
    import re
    m = re.search(r'_(\d{3,4})C_', f)
    sp_nom = int(m.group(1)) if m else round(sp)
    metrics = control_metrics(f'{wd}/run-plots/{f}', sp_nom)
    metrics['run'] = run_id
    metrics['nominal_setpoint_C'] = sp_nom
    results.append(metrics)

m_df = pd.DataFrame(results)
print(m_df.to_string())

   setpoint_C  rise_10_90_s  overshoot_C  settle_to_band_s  soak_mean_C  soak_sd_C  soak_max_dev_C  soak_duration_min  soak_drift_C_per_hr  soak_n_points                               run  nominal_setpoint_C
0        1400        1347.5         59.0            1658.5  1399.628866   3.418972            10.0          11.033333           -77.294753            291    IFrun032_Ni4N5_022_1400C_10min                1400
1        1300        1134.0         11.0            1187.0  1299.935815   3.477210            10.0           7.033333             7.502271            779       IFrun038_Ni4N5_025_1300C_1h                1300
2        1200        2722.5         19.0            2784.5  1200.389291   3.694262            10.0         361.166667            -0.194806          42151       IFrun039_Ni4N5_026_1200C_6h                1200
3        1250        1202.5         11.0            6198.5  1250.031788   2.331442            10.0         278.283333             0.041778          33283       IFrun040_Ni4N5_027_1250C_6h                1250
4        1200         610.0         24.0            5165.0  1199.960014   6.253143            10.0         720.500000            -0.029723           5852      IFrun049_Ni4N5_034_1200C_12h                1200
5        1400        1150.0         13.0            1250.0  1401.654607   3.408396            10.0         720.000000            -0.003257           8596  IFrun072_Ni4N5_079,080_1400C_12h                1400
6        1300        1135.0         12.0            1262.0  1302.081552   2.995696            10.0         720.700000            -0.021056          43224      IFrun079_Ni4N5_084_1300C_12h                1300
7        1325        2500.0         25.0           12090.0  1326.336370   5.495601            10.0        2400.333333            -0.028353           9439      IFrun080_Ni200_017_1325C_40h                1325
8        1325        1130.0          9.0            1182.0  1326.486637   1.480805            10.0        1198.016667            -0.004300          71879      IFrun081_Ni200_015_1325C_20h                1325

In [9]:
# Power -> steady-state-T calibration: pull soak-mean power vs soak-mean T for each run
def soak_power(csv_path, setpoint, deadband_C=10):
    d = pd.read_csv(csv_path)
    in_band = np.abs(d['temperature_C'] - setpoint) <= deadband_C
    if not in_band.any():
        return None
    sub = d[in_band]
    return {'soak_mean_T': sub['temperature_C'].mean(),
            'soak_mean_P_mA': sub['power_mA'].mean(),
            'soak_sd_P_mA': sub['power_mA'].std(ddof=1),
            'n': len(sub)}

cal = []
for f in csvs:
    run_id = f.replace('.csv','')
    import re
    m = re.search(r'_(\d{3,4})C_', f)
    if not m:
        continue
    sp = int(m.group(1))
    res = soak_power(f'{wd}/run-plots/{f}', sp)
    if res:
        res['run'] = run_id
        res['setpoint_C'] = sp
        # detect material
        res['material'] = 'Ni200' if 'Ni200' in run_id else 'Ni4N5'
        res['has_flow'] = df[df['run']==run_id]['has_flow'].values[0]
        cal.append(res)

cal_df = pd.DataFrame(cal)
print(cal_df.to_string())

   soak_mean_T  soak_mean_P_mA  soak_sd_P_mA      n                               run  setpoint_C material has_flow
0  1399.628866        0.744061      0.032157    291    IFrun032_Ni4N5_022_1400C_10min        1400    Ni4N5       no
1  1299.935815        0.578559      0.025064    779       IFrun038_Ni4N5_025_1300C_1h        1300    Ni4N5       no
2  1200.389291        0.439892      0.005533  42151       IFrun039_Ni4N5_026_1200C_6h        1200    Ni4N5       no
3  1250.031788        0.488826      0.005748  33283       IFrun040_Ni4N5_027_1250C_6h        1250    Ni4N5       no
4  1199.960014        0.657769      0.039044   5852      IFrun049_Ni4N5_034_1200C_12h        1200    Ni4N5       no
5  1401.654607        2.035186      0.045337   8596  IFrun072_Ni4N5_079,080_1400C_12h        1400    Ni4N5      yes
6  1302.081552        1.614017      0.051432  43224      IFrun079_Ni4N5_084_1300C_12h        1300    Ni4N5      yes
7  1326.336370        1.102567      0.051934   9439      IFrun080_Ni200_017_1325C_40h        1325    Ni200      yes
8  1326.486637        1.053603      0.019182  71879      IFrun081_Ni200_015_1325C_20h        1325    Ni200      yes

In [10]:
# Quick read of validation section TODOs in paper.tex
import re
with open(f'{wd}/paper.tex') as f:
    tex = f.read()
# Find validation / linkage table sections
for m in re.finditer(r'(?i)(validation|linkage|TODO|specimen|table)', tex):
    pass
# Print sections around 'TODO'
for m in re.finditer(r'TODO', tex):
    s = max(0, m.start()-200); e = min(len(tex), m.end()+400)
    print('---')
    print(tex[s:e])

---
em}
\usepackage[colorlinks=true,allcolors=blue]{hyperref}
\usepackage{gensymb} % \degree, \celsius
\usepackage[htt]{hyphenat} % allow long \texttt{} paths to break across lines
\sloppy

% Lightweight TODO marker so unresolved items remain visible in the compiled PDF.
\newcommand{\todo}[1]{{\color{red}\textbf{[TODO: #1]}}}

% Convenience column types for wide tables.
\newcolumntype{L}[1]{>{\raggedright\arraybackslash}p{#1}}
\newcolumntype{R}[1]{>{\raggedleft\arraybackslash}p{#1}}

\journal{HardwareX}

\begin{document}

\begin{frontmatter}

\title{Retrofitting a commercial RF induction generator int
---
htt]{hyphenat} % allow long \texttt{} paths to break across lines
\sloppy

% Lightweight TODO marker so unresolved items remain visible in the compiled PDF.
\newcommand{\todo}[1]{{\color{red}\textbf{[TODO: #1]}}}

% Convenience column types for wide tables.
\newcolumntype{L}[1]{>{\raggedright\arraybackslash}p{#1}}
\newcolumntype{R}[1]{>{\raggedleft\arraybackslash}p{#1}}

\journal{HardwareX}

\begin{document}

\begin{frontmatter}

\title{Retrofitting a commercial RF induction generator into a
computer-controlled, vacuum-integrated annealing system for reactive-metal
grain growth}

\author[byu]{Ster

In [11]:
# Find validation section
idx = tex.lower().find('validation')
while idx != -1:
    print(idx, repr(tex[idx:idx+120]))
    idx = tex.lower().find('validation', idx+1)

2616 'validation plan based on power$\\rightarrow$temperature\ncalibration, ramp/soak control performance, and SEM/EBSD microstr'
29848 'Validation and characterization}\n%==============================================================\n\nThe repository contain'
30293 'validation package targets five figures, each with quantitative metrics\nrather than qualitative claims.\n\n\\paragraph{Figu'
31989 'validation (SEM + EBSD).} The furnace exists\nto change microstructure, so the key validation is \\textbf{real microstruct'
32071 'validation is \\textbf{real microstructural data}:\nSEM micrographs of as-received vs. annealed samples (e.g. Ni200 / Ni4N'

In [12]:
print(tex[29800:34500])

======================================
\section{Validation and characterization}
%==============================================================

The repository contains 100+ logged runs (\texttt{docs/data\_log/}, IFrun001--100)
across Ni200, Ni4N5, YSZ, and Pd thermal-evaporation experiments, with temperatures
of $\sim$900--1400\,\celsius{} and soak durations from minutes to $\sim$40\,h, each
with \texttt{.xlsx}/\texttt{.txt}/\texttt{.lvm} traces and some photos. The minimum
publishable validation package targets five figures, each with quantitative metrics
rather than qualitative claims.

\paragraph{Figure 1 --- System overview.} A labeled photograph/composite of generator,
controller, chiller, coil, quartz chamber, pyrometer line-of-sight, vacuum station,
and control computer.

\paragraph{Figure 2 --- Power-command $\rightarrow$ temperature calibration.} For a
fixed sample/crucible geometry, steady-state temperature at several analog command
values spanning the useful range, ideally $n \ge 3$ runs per setpoint reported as mean
$\pm$ SD. Plot analog command (mA / scaled \%) vs. pyrometer temperature (\celsius)
with between-run error bars; fit a model only if the data justify it, and show the
operationally linear region explicitly. Hold coil geometry, crucible, optical
alignment, vacuum level, and sample type fixed; state the pyrometer's valid range and
calibration assumptions.

\paragraph{Figure 3 --- Representative ramp/soak with control error.} One
representative anneal (e.g. Ni at $\sim$1200\,\celsius) plotting setpoint and measured
temperature vs. time, parsed from a data log via \texttt{plotheatcurve.m} or a Python
equivalent. Quantify \textbf{rise time, overshoot, settling time, soak mean
temperature, soak SD/RMS error, and maximum absolute deviation during soak.}

\paragraph{Figure 4 --- Repeatability across runs.} The same programmed profile run
$\ge 3$ times on the same setup; overlay the traces and report soak mean temperature,
between-run SD, coefficient of variation, and any long-soak drift. Use archived runs
only if they are truly same-profile/geometry/material/sensor, and state this
explicitly.

\paragraph{Figure 5 --- Microstructural validation (SEM + EBSD).} The furnace exists
to change microstructure, so the key validation is \textbf{real microstructural data}:
SEM micrographs of as-received vs. annealed samples (e.g. Ni200 / Ni4N5) and EBSD
inverse-pole-figure and grain-boundary maps for at least one annealed condition~\cite{liu2021studyofgrain,alogab2007theinfluenceof}.
Quantify grain size properly: number of grains analyzed, equivalent-circle-diameter or
intercept metric, median + IQR (or mean $\pm$ SD), segmentation/cleanup criteria,
minimum-grain-area threshold, and whether twins are merged or separated. Compare
as-received vs. annealed descriptively (and statistically only where replicate
specimens justify it), and, where multiple runs exist, plot grain size vs. soak
temperature/time.

\paragraph{Suggested controls} that build reviewer trust: open-loop vs. closed-loop
on the same target cycle; vacuum vs. inert-gas backfill mode; directly-coupled metal
vs. susceptor-mediated ceramic heating; and long-soak (multi-hour) stability.

\paragraph{Specimen $\leftrightarrow$ thermal-history linkage.} Each microstructure
specimen will be tied to its exact run via a table:

\begin{table*}[ht]
\scriptsize
\setlength{\tabcolsep}{3pt}
\begin{tabularx}{\linewidth}{l l l R{0.06\linewidth} l L{0.13\linewidth} l X}
\toprule
\textbf{Specimen} & \textbf{Material} & \textbf{Run ID} & \textbf{Soak T} & \textbf{Soak time} & \textbf{Atmosphere} & \textbf{Cooling} & \textbf{Grain size (as-recv $\rightarrow$ annealed)} \\
\midrule
\todo{} & \todo{} & \todo{} & \todo{} & \todo{} & \todo{} & \todo{} & \todo{} \\
\bottomrule
\end{tabularx}
\end{table*}

\todo{select canonical run IDs from docs/data\_log/; add the SEM/EBSD image files
(source candidate micrographs from docs/student-work/RyanWeber.pdf) and the parsed
thermal traces under paper/figures/.}

%==============================================================
\section{Safety}
%==============================================================

The system combines high voltage/RF, high vacuum, high temperature, and water
cooling; the principal hazards and mitigations are summarized below.

\begin{table*}[ht]
\small
\begin{tabularx}{\linewidth}{L{0.16\linewidth} L{0.22\linewidth} L{0.16\linewidth} X}
\toprule
\textbf{Hazard} & \textbf{Failure mode} & \textbf{Consequence} & \textbf{Mitigation} \\
\midrule
High voltage / RF field & Contact with coil or induced currents in nearby conductors & Electric shock, burns & Keep conductive objects/electronics $\ge$6--12\,in fr

In [13]:
print(tex[30900:32800])

ometer temperature (\celsius)
with between-run error bars; fit a model only if the data justify it, and show the
operationally linear region explicitly. Hold coil geometry, crucible, optical
alignment, vacuum level, and sample type fixed; state the pyrometer's valid range and
calibration assumptions.

\paragraph{Figure 3 --- Representative ramp/soak with control error.} One
representative anneal (e.g. Ni at $\sim$1200\,\celsius) plotting setpoint and measured
temperature vs. time, parsed from a data log via \texttt{plotheatcurve.m} or a Python
equivalent. Quantify \textbf{rise time, overshoot, settling time, soak mean
temperature, soak SD/RMS error, and maximum absolute deviation during soak.}

\paragraph{Figure 4 --- Repeatability across runs.} The same programmed profile run
$\ge 3$ times on the same setup; overlay the traces and report soak mean temperature,
between-run SD, coefficient of variation, and any long-soak drift. Use archived runs
only if they are truly same-profile/geometry/material/sensor, and state this
explicitly.

\paragraph{Figure 5 --- Microstructural validation (SEM + EBSD).} The furnace exists
to change microstructure, so the key validation is \textbf{real microstructural data}:
SEM micrographs of as-received vs. annealed samples (e.g. Ni200 / Ni4N5) and EBSD
inverse-pole-figure and grain-boundary maps for at least one annealed condition~\cite{liu2021studyofgrain,alogab2007theinfluenceof}.
Quantify grain size properly: number of grains analyzed, equivalent-circle-diameter or
intercept metric, median + IQR (or mean $\pm$ SD), segmentation/cleanup criteria,
minimum-grain-area threshold, and whether twins are merged or separated. Compare
as-received vs. annealed descriptively (and statistically only where replicate
specimens justify it), and, where multiple runs exist, plot grain size vs. soak
temperature/time.

\paragraph{Suggested controls} that

In [14]:
# Now let's check DATA_INVENTORY for sample IDs & micrograph correlation
with open(f'{wd}/DATA_INVENTORY.md') as f:
    inv = f.read()
print(len(inv))
print(inv[:3000])

9245
# Experimental data inventory (auto-generated)

Generated by `paper/build_data_inventory.py` from the binary data files in
`docs/`. This summarizes what already exists **without any new experiments**,
to assess feasibility of a traditional (non-HardwareX) journal contribution.

## Summary

- **Total files under `docs/data_log/`:** 102
- **Files with a parseable material/condition label:** 102
- **Materials (by labeled file count):** Ni4N5 (64), Ni200 (11), crucible (8), Pd (3)
- **Soak temperatures observed (°C):** 900, 1100, 1150, 1200, 1250, 1300, 1325, 1350, 1400
- **Data file types:** xlsx (47), txt (26), jpg (15), lvm (5), png (4), pptx (1), crtx (1), csv (1), tdms (1), tdms_index (1)

### Distinct run IDs by material

- **Ni200:** 7 runs — IFrun001, IFrun002, IFrun003, IFrun004, IFrun005, IFrun080, IFrun081
- **Ni4N5:** 36 runs — IFrun006, IFrun007, IFrun008, IFrun009, IFrun016, IFrun017, IFrun018, IFrun019, IFrun020, IFrun032, IFrun034, IFrun038, IFrun039, IFrun040, IFrun043, IFrun049, IFrun052, IFrun054, IFrun055, IFrun056, IFrun057, IFrun058, IFrun059, IFrun060, IFrun071, IFrun072, IFrun074, IFrun075, IFrun076, IFrun077, IFrun078, IFrun079, IFrun082, IFrun083, IFrun084, IFrun085
- **Pd:** 2 runs — IFRun078, IFrun073
- **crucible:** 4 runs — IFrun035, IFrun036, IFrun037, IFrun043

## Characterization / supporting assets

- `docs/student-work/RyanWeber.pdf` — 1877 KB
- `docs/equipment-reference/` — 7 file(s)
- `docs/ThermalEvaporation/` — 4 file(s)

## Labeled runs (material + soak condition parsed from filename)

| Run / file | Material | Soak T (°C) | Soak time | Type |
|------------|----------|------------:|-----------|------|
| data_log/IFrun001-020/IFrun016_Ni4N5_010.xlsx | Ni4N5 | — | — | xlsx |
| data_log/IFrun001-020/IFrun017_Ni4N5_011.xlsx | Ni4N5 | — | — | xlsx |
| data_log/IFrun001-020/IFrun018_Ni4N5_011.txt | Ni4N5 | — | — | txt |
| data_log/IFrun001-020/IFrun018_Ni4N5_011.xlsx | Ni4N5 | — | — | xlsx |
| data_log/IFrun001-020/IFrun019_Ni4N5_012.txt | Ni4N5 | — | — | txt |
| data_log/IFrun001-020/IFrun019_Ni4N5_012.xlsx | Ni4N5 | — | — | xlsx |
| data_log/IFrun001-020/IFrun020_Ni4N5_013.xlsx | Ni4N5 | — | — | xlsx |
| data_log/IFrun001-020/IFrun020_Ni4N5_013_1250C_1h.txt | Ni4N5 | 1250 | 1h | txt |
| data_log/IFrun001-020/Ni200_001_IFrun001.lvm | Ni200 | — | — | lvm |
| data_log/IFrun001-020/Ni200_001_IFrun002.lvm | Ni200 | — | — | lvm |
| data_log/IFrun001-020/Ni200_001_IFrun003.lvm | Ni200 | — | — | lvm |
| data_log/IFrun001-020/Ni200_001_IFrun004.lvm | Ni200 | — | — | lvm |
| data_log/IFrun001-020/Ni200_001_IFrun004.xlsx | Ni200 | — | — | xlsx |
| data_log/IFrun001-020/Ni200_001_IFrun005.lvm | Ni200 | — | — | lvm |
| data_log/IFrun001-020/Ni200_001_IFrun005.xlsx | Ni200 | — | — | xlsx |
| data_log/IFrun001-020/Ni4N5_001b_IFrun006.xlsx | Ni4N5 | — | — | xlsx |
| data_log/IFrun001-020/Ni4N5_002_IFrun007.xlsx | Ni4N5 | — | — | xlsx |
| data_log/IFrun001-020/Ni4N5_002_IFrun008.PNG | Ni4N5 | — | — | png |
| data_log/IFrun001-020/N

In [15]:
print(inv[5000:9245])

data_log/IFrun041-060/IFrun052_Ni4N5_040_1200C_12h.xlsx | Ni4N5 | 1200 | 12h | xlsx |
| data_log/IFrun041-060/IFrun054_Ni4N5_042,044_1200C_12h.txt | Ni4N5 | 1200 | 12h | txt |
| data_log/IFrun041-060/IFrun054_Ni4N5_042,044_1200C_12h.xlsx | Ni4N5 | 1200 | 12h | xlsx |
| data_log/IFrun041-060/IFrun055_Ni4N5_045,046_1200C_12h.txt | Ni4N5 | 1200 | 12h | txt |
| data_log/IFrun041-060/IFrun055_Ni4N5_045,046_1200C_12h.xlsx | Ni4N5 | 1200 | 12h | xlsx |
| data_log/IFrun041-060/IFrun056_Ni4N5_047,048_1200C_12h (enterprise1.sterling@gmail.com).xlsx | Ni4N5 | 1200 | 12h | xlsx |
| data_log/IFrun041-060/IFrun056_Ni4N5_047,048_1200C_12h.txt | Ni4N5 | 1200 | 12h | txt |
| data_log/IFrun041-060/IFrun056_Ni4N5_047,048_1200C_12h.xlsx | Ni4N5 | 1200 | 12h | xlsx |
| data_log/IFrun041-060/IFrun057_Ni4N5_049,050_1200C_12h - Copy.xlsx | Ni4N5 | 1200 | 12h | xlsx |
| data_log/IFrun041-060/IFrun057_Ni4N5_049,050_1200C_12h.txt | Ni4N5 | 1200 | 12h | txt |
| data_log/IFrun041-060/IFrun057_Ni4N5_049,050_1200C_12h.xlsx | Ni4N5 | 1200 | 12h | xlsx |
| data_log/IFrun041-060/IFrun058_Ni4N5_051,052_1200C_12h.txt | Ni4N5 | 1200 | 12h | txt |
| data_log/IFrun041-060/IFrun058_Ni4N5_051,052_1200C_12h.xlsx | Ni4N5 | 1200 | 12h | xlsx |
| data_log/IFrun041-060/IFrun059_Ni4N5_053,054_1200C_12h.txt | Ni4N5 | 1200 | 12h | txt |
| data_log/IFrun041-060/IFrun059_Ni4N5_053,054_1200C_12h.xlsx | Ni4N5 | 1200 | 12h | xlsx |
| data_log/IFrun041-060/IFrun059_Ni4N5_053.jpg | Ni4N5 | — | — | jpg |
| data_log/IFrun041-060/IFrun060_Ni4N5_056,057_1200C_12h.txt | Ni4N5 | 1200 | 12h | txt |
| data_log/IFrun041-060/IFrun060_Ni4N5_056,057_1200C_12h.xlsx | Ni4N5 | 1200 | 12h | xlsx |
| data_log/IFrun061-080/IFRun078_PdRamping.PNG | Pd | — | — | png |
| data_log/IFrun061-080/IFrun071_Ni4N5_077,078_1350C_12h.xlsx | Ni4N5 | 1350 | 12h | xlsx |
| data_log/IFrun061-080/IFrun072_Ni4N5_079,080_1400C_12h.xlsx | Ni4N5 | 1400 | 12h | xlsx |
| data_log/IFrun061-080/IFrun073_evapDryRun_900C_10min.txt | Pd | 900 | 10min | txt |
| data_log/IFrun061-080/IFrun073_evapDryRun_900C_10min.xlsx | Pd | 900 | 10min | xlsx |
| data_log/IFrun061-080/IFrun074_evap_Ni4N5_053_Pd_001a_900C_10min.txt | Ni4N5 | 900 | 10min | txt |
| data_log/IFrun061-080/IFrun074_evap_Ni4N5_053_Pd_001a_900C_10min.xlsx | Ni4N5 | 900 | 10min | xlsx |
| data_log/IFrun061-080/IFrun075_evap_Ni4N5_053_Pd_001a_900C_10min.txt | Ni4N5 | 900 | 10min | txt |
| data_log/IFrun061-080/IFrun075_evap_Ni4N5_053_Pd_001a_900C_10min.xlsx | Ni4N5 | 900 | 10min | xlsx |
| data_log/IFrun061-080/IFrun076_evap_Ni4N5_053_Pd_001a_1100C_10min.txt | Ni4N5 | 1100 | 10min | txt |
| data_log/IFrun061-080/IFrun076_evap_Ni4N5_053_Pd_001a_1100C_10min.xlsx | Ni4N5 | 1100 | 10min | xlsx |
| data_log/IFrun061-080/IFrun077_evap_Ni4N5_053_Pd_001a_1200C_10min.txt | Ni4N5 | 1200 | 10min | txt |
| data_log/IFrun061-080/IFrun077_evap_Ni4N5_053_Pd_001a_1200C_10min.xlsx | Ni4N5 | 1200 | 10min | xlsx |
| data_log/IFrun061-080/IFrun078_evap_Ni4N5_053_Pd_001a_1300C_10min.txt | Ni4N5 | 1300 | 10min | txt |
| data_log/IFrun061-080/IFrun078_evap_Ni4N5_053_Pd_001a_1300C_10min.xlsx | Ni4N5 | 1300 | 10min | xlsx |
| data_log/IFrun061-080/IFrun079_Ni4N5_084_1300C_12h.txt | Ni4N5 | 1300 | 12h | txt |
| data_log/IFrun061-080/IFrun079_Ni4N5_084_1300C_12h.xlsx | Ni4N5 | 1300 | 12h | xlsx |
| data_log/IFrun061-080/IFrun080_Ni200_017_1325C_40h.txt | Ni200 | 1325 | 40h | txt |
| data_log/IFrun061-080/IFrun080_Ni200_017_1325C_40h.xlsx | Ni200 | 1325 | 40h | xlsx |
| data_log/IFrun081-100/IFrun081_Ni200_015_1325C_20h.txt | Ni200 | 1325 | 20h | txt |
| data_log/IFrun081-100/IFrun081_Ni200_015_1325C_20h.xlsx | Ni200 | 1325 | 20h | xlsx |
| data_log/IFrun081-100/IFrun082_Ni4N5_081_1300C_20h.txt | Ni4N5 | 1300 | 20h | txt |
| data_log/IFrun081-100/IFrun082_Ni4N5_081_1300C_20h.xlsx | Ni4N5 | 1300 | 20h | xlsx |
| data_log/IFrun081-100/IFrun083_Ni4N5_083_1300C_20h.xlsx | Ni4N5 | 1300 | 20h | xlsx |
| data_log/IFrun081-100/IFrun083_Ni4N5_085_1300C_20h.txt | Ni4N5 | 1300 | 20h | txt |
| data_log/IFrun081-100/IFrun084_Ni4N5_086_1300C_20h.txt | Ni4N5 | 1300 | 20h | txt |
| data_log/IFrun081-100/IFrun084_Ni4N5_086_1300C_20h.xlsx | Ni4N5 | 1300 | 20h | xlsx |
| data_log/IFrun081-100/IFrun085_Ni4N5_087_1300C_20h.xlsx | Ni4N5 | 1300 | 20h | xlsx |

In [16]:
# Print the unbroken cohort details with sample IDs from filenames
cohort_files = [
    ('IFrun052','Ni4N5_040'),
    ('IFrun054','Ni4N5_042,044'),
    ('IFrun055','Ni4N5_045,046'),
    ('IFrun056','Ni4N5_047,048'),
    ('IFrun057','Ni4N5_049,050'),
    ('IFrun058','Ni4N5_051,052'),
    ('IFrun059','Ni4N5_053,054'),
    ('IFrun060','Ni4N5_056,057'),
]
print('IFrun052-060 cohort: 8 same-profile, same-material (Ni4N5), same-geometry (Ar/N2 flow=yes per summary), same-target (1200°C/12h)')
print('Specimen IDs included: Ni4N5_040, 042, 044, 045, 046, 047, 048, 049, 050, 051, 052, 053, 054, 056, 057  (n=15 specimens across 8 runs)')

IFrun052-060 cohort: 8 same-profile, same-material (Ni4N5), same-geometry (Ar/N2 flow=yes per summary), same-target (1200°C/12h)
Specimen IDs included: Ni4N5_040, 042, 044, 045, 046, 047, 048, 049, 050, 051, 052, 053, 054, 056, 057  (n=15 specimens across 8 runs)

In [17]:
# Stats for the cohort - control metrics already computed only for IFrun049 (a 1200C/12h but NOT in 052-060)
# Compute soak stats for the cohort using run_summary only since per-run CSVs only exist for IFrun049 in that family
coh_summary = df[df['run'].isin([c[0]+f'_{c[1]}_1200C_12h' for c in cohort_files])].copy()
print(coh_summary[['run','duration_min','peak_temp_C','soak_temp_C','has_flow']].to_string())
print()
print(f"Cohort n = {len(coh_summary)} runs")
print(f"Soak T (peak-of-soak readout): mean = {coh_summary['soak_temp_C'].mean():.2f} °C, SD = {coh_summary['soak_temp_C'].std():.2f} °C, range = [{coh_summary['soak_temp_C'].min():.1f}, {coh_summary['soak_temp_C'].max():.1f}]")
print(f"Peak T (overshoot peak): mean = {coh_summary['peak_temp_C'].mean():.2f} °C, SD = {coh_summary['peak_temp_C'].std():.2f}")
print(f"Soak duration: mean = {coh_summary['duration_min'].mean():.1f} min, SD = {coh_summary['duration_min'].std():.1f}")
print(f"CoV(soak T) = {coh_summary['soak_temp_C'].std()/coh_summary['soak_temp_C'].mean()*100:.3f}%")

                                 run  duration_min  peak_temp_C  soak_temp_C has_flow
22      IFrun052_Ni4N5_040_1200C_12h         756.6       1206.8       1199.8      yes
23  IFrun054_Ni4N5_042,044_1200C_12h         760.0       1227.0       1201.3      yes
24  IFrun055_Ni4N5_045,046_1200C_12h         778.3       1218.4       1204.1      yes
26  IFrun056_Ni4N5_047,048_1200C_12h         760.0       1209.1       1200.6      yes
28  IFrun057_Ni4N5_049,050_1200C_12h         800.0       1210.2       1201.2      yes
29  IFrun058_Ni4N5_051,052_1200C_12h         758.3       1210.5       1200.9      yes
30  IFrun059_Ni4N5_053,054_1200C_12h         758.3       1209.0       1200.3      yes
31  IFrun060_Ni4N5_056,057_1200C_12h         758.3       1209.7       1200.8      yes

Cohort n = 8 runs
Soak T (peak-of-soak readout): mean = 1201.12 °C, SD = 1.30 °C, range = [1199.8, 1204.1]
Peak T (overshoot peak): mean = 1212.59 °C, SD = 6.74
Soak duration: mean = 766.2 min, SD = 15.3
CoV(soak T) = 0.108%

In [18]:
# Quick check: long-soak runs (Ni200 20h and 40h)
ls = df[df['run'].isin(['IFrun080_Ni200_017_1325C_40h','IFrun081_Ni200_015_1325C_20h','IFrun085_Ni4N5_087_1300C_20h'])]
print(ls.to_string())
# Also: 1300C 12h Ni4N5 IFrun079, 1400C 12h IFrun072 - 12-hour soaks
print()
print('From per-run CSV metrics for long soaks:')
print(m_df[m_df['run'].isin(['IFrun080_Ni200_017_1325C_40h','IFrun081_Ni200_015_1325C_20h','IFrun079_Ni4N5_084_1300C_12h','IFrun072_Ni4N5_079,080_1400C_12h'])].to_string())

                             run                                                        source  points  duration_min  peak_temp_C  soak_temp_C has_flow                       run_key
41  IFrun080_Ni200_017_1325C_40h  docs/data_log/IFrun061-080/IFrun080_Ni200_017_1325C_40h.xlsx   14900        2483.2       1349.9       1330.7      yes  IFrun080_Ni200_017_1325C_40h
42  IFrun081_Ni200_015_1325C_20h  docs/data_log/IFrun081-100/IFrun081_Ni200_015_1325C_20h.xlsx   74500        1241.7       1334.2       1326.4      yes  IFrun081_Ni200_015_1325C_20h
46  IFrun085_Ni4N5_087_1300C_20h  docs/data_log/IFrun081-100/IFrun085_Ni4N5_087_1300C_20h.xlsx     700          11.7        799.8        799.5      yes  IFrun085_Ni4N5_087_1300C_20h

From per-run CSV metrics for long soaks:
   setpoint_C  rise_10_90_s  overshoot_C  settle_to_band_s  soak_mean_C  soak_sd_C  soak_max_dev_C  soak_duration_min  soak_drift_C_per_hr  soak_n_points                               run  nominal_setpoint_C
5        1400        1150.0         13.0            1250.0  1401.654607   3.408396            10.0         720.000000            -0.003257           8596  IFrun072_Ni4N5_079,080_1400C_12h                1400
6        1300        1135.0         12.0            1262.0  1302.081552   2.995696            10.0         720.700000            -0.021056          43224      IFrun079_Ni4N5_084_1300C_12h                1300
7        1325        2500.0         25.0           12090.0  1326.336370   5.495601            10.0        2400.333333            -0.028353           9439      IFrun080_Ni200_017_1325C_40h                1325
8        1325        1130.0          9.0            1182.0  1326.486637   1.480805            10.0        1198.016667            -0.004300          71879      IFrun081_Ni200_015_1325C_20h                1325

In [19]:
# check IFrun080 in summary vs per-run CSV - summary says soak_temp_C 1330.7 from xlsx, CSV says 1326.3 mean during in-band
# The summary uses peak-of-soak, per-run CSV gives mean during deadband - this is fine

# IFrun085 - says 1300C 20h but soak_temp_C 799 - so it's incomplete (cut off at warmup) — flag that.
# Confirm by reading the raw xlsx? Not necessary; we already note it.

# Check what micrograph files RyanWeber.pdf might cover. Re-read briefly.
import re
# Search inv for jpg/png references in data_log
jpgs = re.findall(r'`?(data_log/[^|`]*\.(?:jpg|png|jpeg|PNG|JPG))', inv)
print(jpgs[:30])
print(len(jpgs))

['data_log/IFrun001-020/Ni4N5_002_IFrun008.PNG', 'data_log/IFrun041-060/IFrun043_extra/IFrun043_Al2O3_postAnneal_crucibleFacing.jpg', 'data_log/IFrun041-060/IFrun043_extra/IFrun043_Ni4N5_028_endOfTest.jpg', 'data_log/IFrun041-060/IFrun043_extra/IFrun043_Ni4N5_028_endOfTest_snapshot.PNG', 'data_log/IFrun041-060/IFrun043_extra/IFrun043_Ni4N5_028_postAnneal_s1.jpg', 'data_log/IFrun041-060/IFrun043_extra/IFrun043_Ni4N5_028_postAnneal_s2.jpg', 'data_log/IFrun041-060/IFrun043_extra/IFrun043_crucible_postAnneal.jpg', 'data_log/IFrun041-060/IFrun043_extra/IFrun043_crucible_postAnneal_interior.jpg', 'data_log/IFrun041-060/IFrun059_Ni4N5_053.jpg', 'data_log/IFrun061-080/IFRun078_PdRamping.PNG']
10

In [20]:
# Also check the run-plots PNGs we have for figures
print(sorted([f for f in os.listdir(f'{wd}/run-plots') if f.endswith('.png')]))

['IFrun032_Ni4N5_022_1400C_10min.png', 'IFrun038_Ni4N5_025_1300C_1h.png', 'IFrun039_Ni4N5_026_1200C_6h.png', 'IFrun040_Ni4N5_027_1250C_6h.png', 'IFrun049_Ni4N5_034_1200C_12h.png', 'IFrun072_Ni4N5_079,080_1400C_12h.png', 'IFrun079_Ni4N5_084_1300C_12h.png', 'IFrun080_Ni200_017_1325C_40h.png', 'IFrun081_Ni200_015_1325C_20h.png']

In [21]:
# Quick power-T calibration assessment - flow-yes runs only (consistent geometry)
flow_runs = cal_df[cal_df['has_flow']=='yes'].copy()
print("Flow-yes runs (consistent gas/coil/optics setup):")
print(flow_runs.to_string())
print()
# Fit simple polynomial T vs power_mA
from numpy.polynomial import polynomial as P
X = flow_runs['soak_mean_P_mA'].values
Y = flow_runs['soak_mean_T'].values
# Fit T = a + b*P
coef = np.polyfit(X, Y, 1)
pred = np.polyval(coef, X)
resid = Y - pred
print(f"Linear fit T = {coef[1]:.1f} + {coef[0]:.1f}*P_mA")
print(f"R^2 = {1 - resid.var()/Y.var():.3f}, residual SD = {resid.std(ddof=2):.1f} °C, n = {len(X)}")
print()
print("Non-flow runs (different optical/setup era — keep separate):")
print(cal_df[cal_df['has_flow']=='no'].to_string())

Flow-yes runs (consistent gas/coil/optics setup):
   soak_mean_T  soak_mean_P_mA  soak_sd_P_mA      n                               run  setpoint_C material has_flow
5  1401.654607        2.035186      0.045337   8596  IFrun072_Ni4N5_079,080_1400C_12h        1400    Ni4N5      yes
6  1302.081552        1.614017      0.051432  43224      IFrun079_Ni4N5_084_1300C_12h        1300    Ni4N5      yes
7  1326.336370        1.102567      0.051934   9439      IFrun080_Ni200_017_1325C_40h        1325    Ni200      yes
8  1326.486637        1.053603      0.019182  71879      IFrun081_Ni200_015_1325C_20h        1325    Ni200      yes

Linear fit T = 1249.5 + 61.8*P_mA
R^2 = 0.440, residual SD = 39.6 °C, n = 4

Non-flow runs (different optical/setup era — keep separate):
   soak_mean_T  soak_mean_P_mA  soak_sd_P_mA      n                             run  setpoint_C material has_flow
0  1399.628866        0.744061      0.032157    291  IFrun032_Ni4N5_022_1400C_10min        1400    Ni4N5       no
1  1299.935815        0.578559      0.025064    779     IFrun038_Ni4N5_025_1300C_1h        1300    Ni4N5       no
2  1200.389291        0.439892      0.005533  42151     IFrun039_Ni4N5_026_1200C_6h        1200    Ni4N5       no
3  1250.031788        0.488826      0.005748  33283     IFrun040_Ni4N5_027_1250C_6h        1250    Ni4N5       no
4  1199.960014        0.657769      0.039044   5852    IFrun049_Ni4N5_034_1200C_12h        1200    Ni4N5       no

In [22]:
# The flow-yes group has Ni200 at lower P than Ni4N5 - that's because Ni4N5 vs Ni200 are different alloys/geometries
# Honest assessment: only the no-flow Ni4N5 set spans 4 setpoints with same setup
nf = cal_df[(cal_df['has_flow']=='no') & (cal_df['material']=='Ni4N5')]
X = nf['soak_mean_P_mA'].values; Y = nf['soak_mean_T'].values
# But IFrun049 (1200/12h) had different soak power, suggesting different load or geometry vs IFrun039 (1200/6h)
# So the calibration is genuinely setup-dependent. Honest message.

print("Ni4N5 no-flow runs at varying setpoints (4 distinct setpoints, n=5 runs):")
print(nf.to_string())
print()
# Note that IFrun049 P (0.658) >> IFrun039 P (0.440) for same nominal 1200°C - this evidences the calibration depends on geometry/era
# This is exactly why the paper should NOT promise a universal power-T calibration

# Repeat fit excluding the 1200/12h IFrun049 outlier (different geometry)
nf2 = nf[~nf['run'].str.contains('IFrun049')]
X = nf2['soak_mean_P_mA'].values; Y = nf2['soak_mean_T'].values
coef = np.polyfit(X, Y, 1)
pred = np.polyval(coef, X)
print(f"Linear fit (excluding IFrun049): T = {coef[1]:.1f} + {coef[0]:.1f}*P_mA, n={len(X)}")
print(f"R^2 = {1 - (Y-pred).var()/Y.var():.4f}")

Ni4N5 no-flow runs at varying setpoints (4 distinct setpoints, n=5 runs):
   soak_mean_T  soak_mean_P_mA  soak_sd_P_mA      n                             run  setpoint_C material has_flow
0  1399.628866        0.744061      0.032157    291  IFrun032_Ni4N5_022_1400C_10min        1400    Ni4N5       no
1  1299.935815        0.578559      0.025064    779     IFrun038_Ni4N5_025_1300C_1h        1300    Ni4N5       no
2  1200.389291        0.439892      0.005533  42151     IFrun039_Ni4N5_026_1200C_6h        1200    Ni4N5       no
3  1250.031788        0.488826      0.005748  33283     IFrun040_Ni4N5_027_1250C_6h        1250    Ni4N5       no
4  1199.960014        0.657769      0.039044   5852    IFrun049_Ni4N5_034_1200C_12h        1200    Ni4N5       no

Linear fit (excluding IFrun049): T = 931.0 + 633.3*P_mA, n=4
R^2 = 0.9914

In [23]:
# Great - in the IFrun032/038/039/040 sub-cohort (no-flow, Ni4N5, same era), P->T is monotonic and well-fit
# This is the honest calibration figure to show for Figure 2.

# Save calibration table + control metrics table to disk for the manuscript prep
out = wd
m_df.to_csv(f'{out}/control_metrics.csv', index=False)
cal_df.to_csv(f'{out}/power_T_calibration.csv', index=False)
print('Saved control_metrics.csv and power_T_calibration.csv')

Saved control_metrics.csv and power_T_calibration.csv